#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VEL.Resource", IsApplication=true)]

namespace VEL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::VEL.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::VEL.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_business = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_library_books_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_local_gas_station_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_my_location_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_new = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_person_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_placeholder = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_refresh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_save = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_settings_black_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_time_to_leave_black_24dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_work_black_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int DVELHomeView = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int ExpDescrTextView = 2131099654;
			
			// aapt resource value: 0x7f060043
			public const int LinearLayout1 = 2131099715;
			
			// aapt resource value: 0x7f060062
			public const int actionDelete = 2131099746;
			
			// aapt resource value: 0x7f06005e
			public const int actionNew = 2131099742;
			
			// aapt resource value: 0x7f060060
			public const int actionRefresh = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int actionSave = 2131099745;
			
			// aapt resource value: 0x7f06005f
			public const int add_vehicle = 2131099743;
			
			// aapt resource value: 0x7f060025
			public const int busExpButton = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int busGotItButton = 2131099683;
			
			// aapt resource value: 0x7f060011
			public const int businessCheckBox = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int businessExpRelativeLayout = 2131099649;
			
			// aapt resource value: 0x7f06005d
			public const int carClubRadioButton = 2131099741;
			
			// aapt resource value: 0x7f060052
			public const int clubRegisteredCheckBox = 2131099730;
			
			// aapt resource value: 0x7f06000a
			public const int costEditText = 2131099658;
			
			// aapt resource value: 0x7f06002d
			public const int createReportButton = 2131099693;
			
			// aapt resource value: 0x7f06003b
			public const int dateEditText = 2131099707;
			
			// aapt resource value: 0x7f060003
			public const int dateLayout = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int dateTextView = 2131099652;
			
			// aapt resource value: 0x7f060051
			public const int descrEditText = 2131099729;
			
			// aapt resource value: 0x7f060050
			public const int descrTextView = 2131099728;
			
			// aapt resource value: 0x7f060048
			public const int distanceTextView = 2131099720;
			
			// aapt resource value: 0x7f06004d
			public const int engineEditText = 2131099725;
			
			// aapt resource value: 0x7f06003c
			public const int engineTextView = 2131099708;
			
			// aapt resource value: 0x7f060000
			public const int fragmentContainer = 2131099648;
			
			// aapt resource value: 0x7f06001e
			public const int imageView2 = 2131099678;
			
			// aapt resource value: 0x7f060026
			public const int imageView3 = 2131099686;
			
			// aapt resource value: 0x7f06002f
			public const int imageView4 = 2131099695;
			
			// aapt resource value: 0x7f060014
			public const int imageView5 = 2131099668;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout2 = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int linearLayout3 = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout4 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int linearLayout5 = 2131099680;
			
			// aapt resource value: 0x7f060027
			public const int linearLayout6 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int linearLayout7 = 2131099688;
			
			// aapt resource value: 0x7f060030
			public const int linearLayout8 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int linearLayout9 = 2131099697;
			
			// aapt resource value: 0x7f06004b
			public const int makeEditText = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int makeTextView = 2131099722;
			
			// aapt resource value: 0x7f06004c
			public const int modelEditText = 2131099724;
			
			// aapt resource value: 0x7f06003a
			public const int modelTextView = 2131099706;
			
			// aapt resource value: 0x7f06001b
			public const int newTripButton = 2131099675;
			
			// aapt resource value: 0x7f060041
			public const int odoEditText = 2131099713;
			
			// aapt resource value: 0x7f06003f
			public const int odoEndEditText = 2131099711;
			
			// aapt resource value: 0x7f060046
			public const int odoEndTextView = 2131099718;
			
			// aapt resource value: 0x7f06003d
			public const int odoStartEditText = 2131099709;
			
			// aapt resource value: 0x7f060045
			public const int odoStartTextView = 2131099717;
			
			// aapt resource value: 0x7f06004f
			public const int odoTextView = 2131099727;
			
			// aapt resource value: 0x7f060055
			public const int odometerEditText = 2131099733;
			
			// aapt resource value: 0x7f060054
			public const int odometerTextView = 2131099732;
			
			// aapt resource value: 0x7f060036
			public const int progressBar = 2131099702;
			
			// aapt resource value: 0x7f06004e
			public const int regoEditText = 2131099726;
			
			// aapt resource value: 0x7f06003e
			public const int regoTextView = 2131099710;
			
			// aapt resource value: 0x7f060012
			public const int relativeLayout1 = 2131099666;
			
			// aapt resource value: 0x7f06002b
			public const int reportGotItbutton = 2131099691;
			
			// aapt resource value: 0x7f060037
			public const int scrollView1 = 2131099703;
			
			// aapt resource value: 0x7f060034
			public const int settingsGotItButton = 2131099700;
			
			// aapt resource value: 0x7f060017
			public const int space1 = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int space2 = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int space3 = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int space4 = 2131099690;
			
			// aapt resource value: 0x7f060033
			public const int space5 = 2131099699;
			
			// aapt resource value: 0x7f06000d
			public const int supplierEditText = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int supplierTextView = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int tableLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int tableRow1 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow3 = 2131099662;
			
			// aapt resource value: 0x7f06002e
			public const int tableRow4 = 2131099694;
			
			// aapt resource value: 0x7f060038
			public const int textView = 2131099704;
			
			// aapt resource value: 0x7f060009
			public const int textView1 = 2131099657;
			
			// aapt resource value: 0x7f060047
			public const int textView10 = 2131099719;
			
			// aapt resource value: 0x7f060019
			public const int textView12 = 2131099673;
			
			// aapt resource value: 0x7f060021
			public const int textView13 = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int textView14 = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int textView15 = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int textView18 = 2131099692;
			
			// aapt resource value: 0x7f060032
			public const int textView19 = 2131099698;
			
			// aapt resource value: 0x7f06000f
			public const int textView2 = 2131099663;
			
			// aapt resource value: 0x7f060035
			public const int textView20 = 2131099701;
			
			// aapt resource value: 0x7f060057
			public const int textView3 = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int textView4 = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int textView5 = 2131099737;
			
			// aapt resource value: 0x7f06005b
			public const int textView6 = 2131099739;
			
			// aapt resource value: 0x7f060016
			public const int textView8 = 2131099670;
			
			// aapt resource value: 0x7f060039
			public const int tripDescrEditText = 2131099705;
			
			// aapt resource value: 0x7f060044
			public const int tripDescrTextView = 2131099716;
			
			// aapt resource value: 0x7f060042
			public const int tripDetailLayout = 2131099714;
			
			// aapt resource value: 0x7f060005
			public const int tripLayout = 2131099653;
			
			// aapt resource value: 0x7f06005a
			public const int vehDescrEditText = 2131099738;
			
			// aapt resource value: 0x7f06001d
			public const int vehExpButton = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int vehGotItButton = 2131099672;
			
			// aapt resource value: 0x7f06005c
			public const int vehRegoEditText = 2131099740;
			
			// aapt resource value: 0x7f060040
			public const int vehRegoTextView = 2131099712;
			
			// aapt resource value: 0x7f060053
			public const int vehicleExpRelativeLayout = 2131099731;
			
			// aapt resource value: 0x7f060010
			public const int vehicleRegoEditText = 2131099664;
			
			// aapt resource value: 0x7f060056
			public const int vehicleScrollView = 2131099734;
			
			// aapt resource value: 0x7f060049
			public const int vehicleTextView = 2131099721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int businessExpFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BusinessExpListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DVELHome = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TripDetailFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TripDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int tripfragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TripListFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TripListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TripsFragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int VehicleDetail = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int VehicleDetailsFragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int vehicleExpFragment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int VehicleExpListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int VehicleList = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int VehicleListFragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int VehicleListItem = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_fragement_list = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int VehicleDetailMenu = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int createtrip_tab_label = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int date_label = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int description_hint = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int distance_label = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int end_odometer_label = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int start_odometer_label = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int triplist_tab_label = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int vehicle_used_hint = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int vehicleexpenses_tab_label = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
