#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DVEL.Resource", IsApplication=true)]

namespace DVEL
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::DVEL.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::DVEL.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::DVEL.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::DVEL.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_business = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_library_books_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_local_gas_station_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_my_location_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_new = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_person_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_placeholder = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_refresh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_save = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_settings_black_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_time_to_leave_black_24dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_work_black_24dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int DVELHomeView = 2131034129;
			
			// aapt resource value: 0x7f050026
			public const int busExpButton = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int busGotItButton = 2131034148;
			
			// aapt resource value: 0x7f05000e
			public const int clubRegisteredCheckBox = 2131034126;
			
			// aapt resource value: 0x7f05002f
			public const int createReportButton = 2131034159;
			
			// aapt resource value: 0x7f05003a
			public const int dateTextView = 2131034170;
			
			// aapt resource value: 0x7f05000d
			public const int descrEditText = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int descrTextView = 2131034124;
			
			// aapt resource value: 0x7f050040
			public const int distanceTextView = 2131034176;
			
			// aapt resource value: 0x7f05003f
			public const int endOdoTextView = 2131034175;
			
			// aapt resource value: 0x7f050007
			public const int engineEditText = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int engineTextView = 2131034118;
			
			// aapt resource value: 0x7f050039
			public const int frameLayout1 = 2131034169;
			
			// aapt resource value: 0x7f05001f
			public const int imageView2 = 2131034143;
			
			// aapt resource value: 0x7f050028
			public const int imageView3 = 2131034152;
			
			// aapt resource value: 0x7f050031
			public const int imageView4 = 2131034161;
			
			// aapt resource value: 0x7f050014
			public const int imageView5 = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout2 = 2131034133;
			
			// aapt resource value: 0x7f05001a
			public const int linearLayout3 = 2131034138;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout4 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int linearLayout5 = 2131034145;
			
			// aapt resource value: 0x7f050029
			public const int linearLayout6 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout7 = 2131034154;
			
			// aapt resource value: 0x7f050032
			public const int linearLayout8 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int linearLayout9 = 2131034163;
			
			// aapt resource value: 0x7f050003
			public const int makeEditText = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int makeTextView = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int modelEditText = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int modelTextView = 2131034116;
			
			// aapt resource value: 0x7f05001b
			public const int newTripButton = 2131034139;
			
			// aapt resource value: 0x7f05000b
			public const int odoEditText = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int odoTextView = 2131034122;
			
			// aapt resource value: 0x7f050038
			public const int progressBar = 2131034168;
			
			// aapt resource value: 0x7f050041
			public const int purposeTextView = 2131034177;
			
			// aapt resource value: 0x7f050009
			public const int regoEditText = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int regoTextView = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int relativeLayout1 = 2131034128;
			
			// aapt resource value: 0x7f05002d
			public const int reportGotItbutton = 2131034157;
			
			// aapt resource value: 0x7f050000
			public const int scrollView1 = 2131034112;
			
			// aapt resource value: 0x7f050036
			public const int settingsGotItButton = 2131034166;
			
			// aapt resource value: 0x7f050017
			public const int space1 = 2131034135;
			
			// aapt resource value: 0x7f05001c
			public const int space2 = 2131034140;
			
			// aapt resource value: 0x7f050023
			public const int space3 = 2131034147;
			
			// aapt resource value: 0x7f05002c
			public const int space4 = 2131034156;
			
			// aapt resource value: 0x7f050035
			public const int space5 = 2131034165;
			
			// aapt resource value: 0x7f05003e
			public const int startOdoTextView = 2131034174;
			
			// aapt resource value: 0x7f050012
			public const int tableLayout1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int tableRow1 = 2131034131;
			
			// aapt resource value: 0x7f05001e
			public const int tableRow2 = 2131034142;
			
			// aapt resource value: 0x7f050027
			public const int tableRow3 = 2131034151;
			
			// aapt resource value: 0x7f050030
			public const int tableRow4 = 2131034160;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			// aapt resource value: 0x7f050019
			public const int textView12 = 2131034137;
			
			// aapt resource value: 0x7f050022
			public const int textView13 = 2131034146;
			
			// aapt resource value: 0x7f050025
			public const int textView14 = 2131034149;
			
			// aapt resource value: 0x7f05002b
			public const int textView15 = 2131034155;
			
			// aapt resource value: 0x7f05002e
			public const int textView18 = 2131034158;
			
			// aapt resource value: 0x7f050034
			public const int textView19 = 2131034164;
			
			// aapt resource value: 0x7f05003c
			public const int textView2 = 2131034172;
			
			// aapt resource value: 0x7f050037
			public const int textView20 = 2131034167;
			
			// aapt resource value: 0x7f05003d
			public const int textView3 = 2131034173;
			
			// aapt resource value: 0x7f050016
			public const int textView8 = 2131034134;
			
			// aapt resource value: 0x7f05003b
			public const int tripDescrTextView = 2131034171;
			
			// aapt resource value: 0x7f05001d
			public const int vehExpButton = 2131034141;
			
			// aapt resource value: 0x7f050018
			public const int vehGotItButton = 2131034136;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateTripDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateTripFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TripFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TripLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TripListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int VehicleExpenseFragment = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int Date = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int business = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int createtrip_tab_label = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int trip = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int triplist_tab_label = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int vehicle = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int vehicleexpenses_tab_label = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
